gfx/env/trainyardup.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardft.tga
gfx/env/trainyardbk.tga
models/de_118shkola/6o4ka2.mdl
models/de_118shkola/AA_PaintPrefab_06_TCH_SMesh.mdl
models/de_118shkola/jb_trashcan.mdl
models/de_118shkola/apartment_mailmess_sparse.mdl
models/de_118shkola/bm_handfat.mdl
models/de_118shkola/brandlol.mdl
models/de_118shkola/chair2.mdl
models/de_118shkola/geo_vedro2.mdl
models/de_118shkola/piano02.mdl
models/de_118shkola/s_shelf.mdl
models/de_118shkola/table01.mdl
models/de_118shkola/Wheebarrow01a.mdl
models/de_118shkola/buzz_lopata.mdl
models/de_118shkola/sidelkachaka1.mdl
sound/de_118shkola/zvonok.wav
models/de_118shkola/ostol4stula.mdl
sound/de_118shkola/ambient_summer.wav
sound/de_118shkola/pa_birdloop.wav
sound/de_118shkola/rnd_dog6.wav
sound/de_118shkola/koridor_v_shkole.wav
sound/de_118shkola/peremena.wav
sound/de_118shkola/peremena2.wav
sound/de_118shkola/pesenka.wav
overviews/de_118shkola.bmp
overviews/de_118shkola.txt
maps/de_118shkola.res
maps/de_118shkola.nav
maps/de_118shkola.txt