//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_rats_caravan
//
// Download @: http://dwl.17buddies.net/link/map/3395/de_rats_caravan.html
//
//////////////////////////////////////////////////////////
gfx/env/de_rats_caravanup.tga
gfx/env/de_rats_caravandn.tga
gfx/env/de_rats_caravanlf.tga
gfx/env/de_rats_caravanrt.tga
gfx/env/de_rats_caravanft.tga
gfx/env/de_rats_caravanbk.tga
 
models/de_rats_caravan/araignee.mdl
models/de_rats_caravan/bouteille1.mdl
models/de_rats_caravan/bouteille2.mdl
models/de_rats_caravan/cola.mdl
models/de_rats_caravan/couteau1.mdl
models/de_rats_caravan/couteau2.mdl
models/de_rats_caravan/couteau3.mdl
models/de_rats_caravan/couverts.mdl
models/de_rats_caravan/gins_block.mdl
models/de_rats_caravan/gins_cactuslo.mdl
models/de_rats_caravan/gins_leafy.mdl
models/de_rats_caravan/hachoir.mdl
models/de_rats_caravan/hauspflanze2.mdl
models/de_rats_caravan/jambon.mdl
models/de_rats_caravan/lampe.mdl
models/de_rats_caravan/pepsi.mdl 
models/de_rats_caravan/Plant.mdl
models/de_rats_caravan/plante2.mdl
models/de_rats_caravan/plante2t.mdl 
models/de_rats_caravan/poulet.mdl
models/de_rats_caravan/ventilo.mdl
 
sound/de_rats_caravan/at_fan.wav
sound/de_rats_caravan/comp2.wav
sound/de_rats_caravan/comp3.wav
sound/de_rats_caravan/crow.wav
sound/de_rats_caravan/debut_tuyau.wav
sound/de_rats_caravan/fallscream.wav
sound/de_rats_caravan/fan2.wav
sound/de_rats_caravan/fin_tuyau.wav
sound/de_rats_caravan/geiger1.wav
sound/de_rats_caravan/geiger2.wav
sound/de_rats_caravan/geiger3.wav
sound/de_rats_caravan/geiger4.wav
sound/de_rats_caravan/geiger5.wav
sound/de_rats_caravan/geiger6.wav
sound/de_rats_caravan/grille.wav
sound/de_rats_caravan/mbigfan.wav
sound/de_rats_caravan/oiseaux1.wav
sound/de_rats_caravan/oiseaux2.wav
sound/de_rats_caravan/oiseaux6.wav
sound/de_rats_caravan/oiseaux7.wav
sound/de_rats_caravan/oiseaux8.wav
sound/de_rats_caravan/oiseaux9.wav
sound/de_rats_caravan/radio.wav
sound/de_rats_caravan/sheep.wav 
sound/de_rats_caravan/trome_voltage.wav
sound/de_rats_caravan/zikmu.wav

sprites/laserbeam.spr
sprites/lgtning.spr
sprites/de_rats_caravan/webstrand.spr
 
overviews/de_rats_caravan.bmp
overviews/de_rats_caravan.txt
